name: sudo-ape

plugins:
  - name: solidity
  - name: notebook
  - name: etherscan

default_ecosystem: ethereum

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.6.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/v4.6.0"

ethereum:
  default_network: mainnet
  mainnet:
    default_provider: alchemy
